### ISSUE TITLE
Document not complete/accurate

### ISSUE THREAD

**Issue by namloc2001** [ibm-cloud-docs/openshift#53]
Hi, I'm trying to follow: https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-qs-roks4 to expose a service via a TLS  ingress. 

The ingress shown in step 3 is not using the `tls` option and thus the ingress will only be presented as http (tcp/80).  Step 5 then shows accessing this ingress via `https`.

I would like steps as to how to setup TLS ingress on OpenShift v4.x on IBM Cloud please, using the default cluster TLS certificate. I am currently having issues with this as it stops both https and http ingress connections from working when I include it.

Here is my configuration:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 3
  labels:
    app.kubernetes.io/name: defectdojo
  name: matt-dd-django
  namespace: sbu-dev
spec:
  rules:
  - host: defectdojo.mattcluster-<hash>-0000.eu-gb.containers.appdomain.cloud
    http:
      paths:
      - backend:
          serviceName: matt-dd-django
          servicePort: http
        path: /
  tls:
  - hosts:
    - defectdojo.mattcluster-<hash>-0000.eu-gb.containers.appdomain.cloud
    secretName: mattcluster-<hash>-0000
status:
  loadBalancer: {}
```

Thanks.
